### ISSUE TITLE
Error during build: vasm1_8d.tar.gz seems to not be found.

### ISSUE THREAD

**Issue by salocinx** [cahirwpz/amigaos-cross-toolchain#102]
Hi.

I am working with Ubuntu 16.04.6 LTS i386 (32-bit version).

I get the following error while executing `# ./toolchain-m68k --prefix=/opt/m68k-amigaos build`:

```
DEBUG: makedir "../../../../opt/m68k-amigaos"
INFO: adding "../../../../opt/m68k-amigaos/lib/python2.7/site-packages" to python site dirs
DEBUG: require_header "ncurses.h"
DEBUG: require_header "python2.7/Python.h"
DEBUG: execute "git submodule init submodules/python-lhafile"
Submodule 'submodules/python-lhafile' (git://github.com/FrodeSolheim/python-lhafile) registered for path 'submodules/python-lhafile'
DEBUG: execute "git submodule update submodules/python-lhafile"
Cloning into 'submodules/python-lhafile'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 157 (delta 6), reused 6 (delta 1), pack-reused 142
Receiving objects: 100% (157/157), 289.46 KiB | 466.00 KiB/s, done.
Resolving deltas: 100% (75/75), done.
Checking connectivity... done.
Submodule path 'submodules/python-lhafile': checked out '8f800bbcb47431f9ed4d36d847621525217a72d8'
DEBUG: makedir ".build-m68k/stamps"
INFO: preparing files for "python-lha"
DEBUG: copytree "submodules/python-lhafile" to ".build-m68k/build/python-lha"
DEBUG: makedir ".build-m68k/build/python-lha"
DEBUG: copy "submodules/python-lhafile/.gitignore" to ".build-m68k/build/python-lha/.gitignore"
DEBUG: copy "submodules/python-lhafile/COPYING.txt" to ".build-m68k/build/python-lha/COPYING.txt"
DEBUG: copy "submodules/python-lhafile/MANIFEST.in" to ".build-m68k/build/python-lha/MANIFEST.in"
DEBUG: copy "submodules/python-lhafile/PKG-INFO" to ".build-m68k/build/python-lha/PKG-INFO"
DEBUG: copy "submodules/python-lhafile/README" to ".build-m68k/build/python-lha/README"
DEBUG: copy "submodules/python-lhafile/README.txt" to ".build-m68k/build/python-lha/README.txt"
DEBUG: copy "submodules/python-lhafile/VERSION" to ".build-m68k/build/python-lha/VERSION"
DEBUG: makedir ".build-m68k/build/python-lha/debian"
DEBUG: copy "submodules/python-lhafile/debian/.gitignore" to ".build-m68k/build/python-lha/debian/.gitignore"
DEBUG: copy "submodules/python-lhafile/debian/changelog" to ".build-m68k/build/python-lha/debian/changelog"
DEBUG: copy "submodules/python-lhafile/debian/compat" to ".build-m68k/build/python-lha/debian/compat"
DEBUG: copy "submodules/python-lhafile/debian/control" to ".build-m68k/build/python-lha/debian/control"
DEBUG: copy "submodules/python-lhafile/debian/copyright" to ".build-m68k/build/python-lha/debian/copyright"
DEBUG: copy "submodules/python-lhafile/debian/python-lhafile.install" to ".build-m68k/build/python-lha/debian/python-lhafile.install"
DEBUG: copy "submodules/python-lhafile/debian/python3-lhafile.install" to ".build-m68k/build/python-lha/debian/python3-lhafile.install"
DEBUG: copy "submodules/python-lhafile/debian/rules" to ".build-m68k/build/python-lha/debian/rules"
DEBUG: makedir ".build-m68k/build/python-lha/debian/source"
DEBUG: copy "submodules/python-lhafile/debian/source/format" to ".build-m68k/build/python-lha/debian/source/format"
DEBUG: makedir ".build-m68k/build/python-lha/lhafile"
DEBUG: copy "submodules/python-lhafile/lhafile/__init__.py" to ".build-m68k/build/python-lha/lhafile/__init__.py"
DEBUG: copy "submodules/python-lhafile/lhafile/lhafile.py" to ".build-m68k/build/python-lha/lhafile/lhafile.py"
DEBUG: makedir ".build-m68k/build/python-lha/lhafile/tests"
DEBUG: copy "submodules/python-lhafile/lhafile/tests/archive_lhaca.lzh" to ".build-m68k/build/python-lha/lhafile/tests/archive_lhaca.lzh"
DEBUG: copy "submodules/python-lhafile/lhafile/tests/archive_lhaplus.lzh" to ".build-m68k/build/python-lha/lhafile/tests/archive_lhaplus.lzh"
DEBUG: copy "submodules/python-lhafile/lhafile/tests/archive_lhaunix_lh5.lzh" to ".build-m68k/build/python-lha/lhafile/tests/archive_lhaunix_lh5.lzh"
DEBUG: copy "submodules/python-lhafile/lhafile/tests/archive_lhaunix_lh6.lzh" to ".build-m68k/build/python-lha/lhafile/tests/archive_lhaunix_lh6.lzh"
DEBUG: copy "submodules/python-lhafile/lhafile/tests/archive_lhaunix_lh7.lzh" to ".build-m68k/build/python-lha/lhafile/tests/archive_lhaunix_lh7.lzh"
DEBUG: copy "submodules/python-lhafile/lhafile/tests/test_lhafile.py" to ".build-m68k/build/python-lha/lhafile/tests/test_lhafile.py"
DEBUG: copy "submodules/python-lhafile/lzhlib.c" to ".build-m68k/build/python-lha/lzhlib.c"
DEBUG: copy "submodules/python-lhafile/python-lhafile.spec" to ".build-m68k/build/python-lha/python-lhafile.spec"
DEBUG: copy "submodules/python-lhafile/setup.py" to ".build-m68k/build/python-lha/setup.py"
DEBUG: makedir "../../../../opt/m68k-amigaos/lib/python2.7/site-packages"
DEBUG: changing environment variable "PYTHONPATH" to "/opt/m68k-amigaos/lib/python2.7/site-packages"
DEBUG: enter directory ".build-m68k/build/python-lha"
DEBUG: execute "/usr/bin/python2.7 setup.py build"
running build
running build_py
creating build
creating build/lib.linux-i686-2.7
creating build/lib.linux-i686-2.7/lhafile
copying lhafile/lhafile.py -> build/lib.linux-i686-2.7/lhafile
copying lhafile/__init__.py -> build/lib.linux-i686-2.7/lhafile
running build_ext
building 'lzhlib' extension
creating build/temp.linux-i686-2.7
/usr/bin/gcc -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=2 -I/usr/include/python2.7 -c lzhlib.c -o build/temp.linux-i686-2.7/lzhlib.o
i686-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-i686-2.7/lzhlib.o -o build/lib.linux-i686-2.7/lzhlib.so
DEBUG: execute "/usr/bin/python2.7 setup.py install --prefix=/opt/m68k-amigaos"
running install
running build
running build_py
running build_ext
running install_lib
copying build/lib.linux-i686-2.7/lzhlib.so -> /opt/m68k-amigaos/lib/python2.7/site-packages
creating /opt/m68k-amigaos/lib/python2.7/site-packages/lhafile
copying build/lib.linux-i686-2.7/lhafile/lhafile.py -> /opt/m68k-amigaos/lib/python2.7/site-packages/lhafile
copying build/lib.linux-i686-2.7/lhafile/__init__.py -> /opt/m68k-amigaos/lib/python2.7/site-packages/lhafile
byte-compiling /opt/m68k-amigaos/lib/python2.7/site-packages/lhafile/lhafile.py to lhafile.pyc
byte-compiling /opt/m68k-amigaos/lib/python2.7/site-packages/lhafile/__init__.py to __init__.pyc
running install_egg_info
Writing /opt/m68k-amigaos/lib/python2.7/site-packages/lhafile-0.2.1-py2.7.egg-info
DEBUG: restoring old value of environment variable "PYTHONPATH"
DEBUG: makedir ".build-m68k/archives"
DEBUG: enter directory ".build-m68k/archives"
INFO: download "https://ftp.gnu.org/gnu/m4/m4-1.4.17.tar.gz" to ".build-m68k/archives/m4-1.4.17.tar.gz"
INFO: download: m4-1.4.17.tar.gz (size: 1820658)
1820658 [100.00%]
INFO: download "https://ftp.gnu.org/gnu/gawk/gawk-3.1.8.tar.gz" to ".build-m68k/archives/gawk-3.1.8.tar.gz"
INFO: download: gawk-3.1.8.tar.gz (size: 2627635)
2627635 [100.00%]
INFO: download "https://ftp.gnu.org/gnu/autoconf/autoconf-2.13.tar.gz" to ".build-m68k/archives/autoconf-2.13.tar.gz"
INFO: download: autoconf-2.13.tar.gz (size: 443844)
443844 [100.00%]
INFO: download "https://ftp.gnu.org/gnu/bison/bison-1.35.tar.gz" to ".build-m68k/archives/bison-1.35.tar.gz"
INFO: download: bison-1.35.tar.gz (size: 770444)
770444 [100.00%]
INFO: download "https://ftp.gnu.org/gnu/texinfo/texinfo-4.12.tar.gz" to ".build-m68k/archives/texinfo-4.12.tar.gz"
INFO: download: texinfo-4.12.tar.gz (size: 2476832)
2476832 [100.00%]
INFO: download "https://ftp.gnu.org/gnu/automake/automake-1.15.tar.gz" to ".build-m68k/archives/automake-1.15.tar.gz"
INFO: download: automake-1.15.tar.gz (size: 2244206)
2244206 [100.00%]
INFO: download "ftp://ftp.uk.freesbie.org/sites/distfiles.gentoo.org/distfiles/flex-2.5.4a.tar.gz" to ".build-m68k/archives/flex-2.5.4.tar.gz"
INFO: download: flex-2.5.4.tar.gz (size: 380995)
380995 [100.00%]
INFO: download "http://www.haage-partner.de/download/AmigaOS/NDK39.lha" to ".build-m68k/archives/NDK_3.9.lha"
INFO: download: NDK_3.9.lha (size: 3082305)
3082305 [100.00%]
INFO: download "ftp://ftp.exotica.org.uk/mirrors/geekgadgets/amiga/m68k/snapshots/990529/bin/libamiga-bin.tgz" to ".build-m68k/archives/libamiga.tar.gz"
INFO: download: libamiga.tar.gz (size: 127977)
127977 [100.00%]
INFO: download "ftp://ftp.exotica.org.uk/mirrors/geekgadgets/amiga/m68k/snapshots/990529/src/libm-5.4-src.tgz" to ".build-m68k/archives/libm-5.4.tar.gz"
INFO: download: libm-5.4.tar.gz (size: 113142)
113142 [100.00%]
INFO: download "http://downloads.sf.net/project/amiga/ixemul.library/48.2/ixemul-src.lha" to ".build-m68k/archives/ixemul-48.2.lha"
INFO: download: ixemul-48.2.lha (size: 2371882)
2371882 [100.00%]
INFO: download "http://server.owl.de/~frank/tags/vasm1_8d.tar.gz" to ".build-m68k/archives/vasm.tar.gz"
Traceback (most recent call last):
  File "./toolchain-m68k", line 785, in <module>
    globals()[action].__call__(*args.args)
  File "./toolchain-m68k", line 326, in build
    download()
  File "./toolchain-m68k", line 251, in download
    fetch(name, url)
  File "/home/nicolas/Downloads/amigaos-cross-toolchain/common.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/home/nicolas/Downloads/amigaos-cross-toolchain/common.py", line 373, in wrapper
    fn(*args, **kwargs)
  File "/home/nicolas/Downloads/amigaos-cross-toolchain/common.py", line 417, in fetch
    download(url, name)
  File "/home/nicolas/Downloads/amigaos-cross-toolchain/common.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/home/nicolas/Downloads/amigaos-cross-toolchain/common.py", line 238, in download
    u = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1235, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1205, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
```
Somebody some idea how to solve?

**Comment by sezero** [comment]
Change that link to http://phoenix.owl.de/tags/vasm1_8d.tar.gz

If you want newer versions, go to http://sun.hasenbraten.de/vbcc/
and take your pick.
