### ISSUE TITLE
HTTP 403 during toolchain-m68k

### ISSUE THREAD

**Issue by OliverUrbann** [cahirwpz/amigaos-cross-toolchain#41]
Fresh clone and executing as described gives:
`
Traceback (most recent call last):
  File "./toolchain-m68k", line 651, in <module>
    globals()[action].__call__(*args.args)
  File "./toolchain-m68k", line 219, in build
    fetch(name, url)
  File "/Users/civic/Documents/Entwicklung/Amiga/amigaos-cross-toolchain/common.py", line 37, in wrapper
    return fn(*args, **kwargs)
  File "/Users/civic/Documents/Entwicklung/Amiga/amigaos-cross-toolchain/common.py", line 350, in wrapper
    fn(*args, **kwargs)
  File "/Users/civic/Documents/Entwicklung/Amiga/amigaos-cross-toolchain/common.py", line 369, in fetch
    download(url, name)
  File "/Users/civic/Documents/Entwicklung/Amiga/amigaos-cross-toolchain/common.py", line 37, in wrapper
    return fn(*args, **kwargs)
  File "/Users/civic/Documents/Entwicklung/Amiga/amigaos-cross-toolchain/common.py", line 232, in download
    u = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
`

**Comment by cahirwpz** [comment]
Which url is it trying to fetch?

**Comment by cahirwpz** [comment]
I've just downloaded the repo on my local Linux box at work and fetch stage passed successfully. Hasn't any firewall software got into your way?

**Comment by OliverUrbann** [comment]
Works again, seems that it was just a temporary problem
